

trigger:
  branches:
    include:
      - dev
  paths:
    exclude:
      - READEME.md

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '596527a0-844e-4fd1-af71-888334b640ff'
  imageRepository: 'tc3-get-contact'
  containerRegistry: 'fiaptech3acr.azurecr.io'
  dockerfilePath: 'Dockerfile'
  k8s-deployment: 'k8s-deployment-yaml'
  k8sPathName: 'k8s'

  kubernetesServiceEndpoint:
  azureSubscription: '7d56ed09-a476-4593-9fbf-0927c0c53f5e'
  kubernetesAzureResourceGroup: fiap-tech3
  kubernetesClusterName: fiapaks
  kubernetesNamespace: tc3
  tag: '$(Build.BuildId)'



vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Show ws files.
          echo $(ls)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

    - job: UploadArtifact
    displayName: "Upload Deployment YAML"
    dependsOn: Build
    steps:
    - script: mkdir -p $(System.DefaultWorkingDirectory)/$(k8sPathName)
      displayName: "Create artifact folder"
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/$(k8sPathName)
        artifact: $(k8s-deployment)
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy Stage
  jobs:
  - job: DeployDatabase
    displayName: Deploy Sql Server to AKS
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildTypo: 'current'
          artifactName: $(k8s-deployment)
          targetPath: $(System.DefaultWorkingDirectory)/$(k8sPathName)
      - task: kubernetes@1
        displayName: "Apply Deployment YAML"
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndppoint: $(kubernetesServiceEndpoint)
          azureSubscription: $(azureSubscription) '7d56ed09-a476-4593-9fbf-0927c0c53f5e'
          resourceGroup: $(kubernetesAzureResourceGroup) fiap-tech3
          kubernetesCluster: $(kubernetesClusterName) fiapaks
          namespace: $(kubernetesNamespace)
          command: 'apply'
          useConfigurableFile: false
          configuration: '$(System.DefaultWorkingDirectory)/$(k8sPathName)/k8s-dev.yaml'