apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-contacts
  namespace: PLACEHOLDER_NAMESPACE
  labels:
    app: get-contacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-contacts
  template:
    metadata:
      labels:
        app: get-contacts
    spec:
      containers:
      - name: get-contacts
        image: PLACEHOLDER_CONTAINER_REGISTRY/PLACEHOLDER_IMAGE_REPOSITORY:PLACEHOLDER_TAG #usar tag e nome do container como variáveis no build para simplificar a reutilização.
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-connection
              key: ConnectionStrings__DefaultConnection
---
apiVersion: v1
kind: Service
metadata:
  name: get-contacts-service
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    app: get-contacts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP