apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
  namespace: tc3
  labels:
    app: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: fiaptech3acr.azurecr.io/sql-server-seed:latest #usar tag e nome do container como variáveis no build para simplificar a reutilização.
        env:
        - name: ACCEPT_EULA # Capturar valores de configuração da aplicação como variaveis do pipe, secrets ou configmaps.
          valueFrom:
            configMapKeyRef:
              name: sql-server-config-map
              key: ACCEPT_EULA
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-secret
              key: MSSQL_SA_PASSWORD
        - name: SVC_PASS
          valueFrom:
            secretKeyRef:
              name: sql-server-secret
              key: SVC_PASS
        ports:
        - containerPort: 1433 # Acho que a porta a ser utilizada aqui é a 80
---
apiVersion: v1 # Preciso desligar o loadBalancer do banco de dados e trocá-lo por um clusterIp
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer