apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-contacts
  namespace: tc3
  labels:
    app: get-contacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-contacts
  template:
    metadata:
      labels:
        app: get-contacts
    spec:
      containers:
      - name: get-contacts
        image: fiaptech3acr.azurecr.io/tc3-get-contact:latest #usar tag e nome do container como variáveis no build para simplificar a reutilização.
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: get-contacts-service
  namespace: tc3
spec:
  selector:
    app: get-contacts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP